### PR TITLE
Merge dev onto master

### LINKED ISSUE #326: Term Start and End Dates are incorrect - causing bad schedule files to be generated.
When generating iCal files, the event dates are weeks off from when the term actually starts and ends. I don't have access to the database, so I'm not sure if it's an issue there or in the code that processes the term dates.

### PR DESCRIPTION
**Pull request by Mstrodl**
Obsoletes #325 
Closes #326, #310, #232

### CODE REVIEW

**Review by jabbate19 — APPROVED** [review]
Dude I was playing minecraft

**Comment by nsp7786** [comment]
#325 was not fully addressed in this PR. 

Change number 2 was not addressed, which generate a single series for a multi-day course (Mon,Web,Fri for example) to simplify calendars (see the [iCal specification for RRULE](https://icalendar.org/iCalendar-RFC-5545/3-8-5-3-recurrence-rule.html)), and resolve #63 .

**Comment by natep-tech** [comment]
#325 was not fully addressed with this PR and shouldn't have been closed yet.

Change number 2, which generates a single series for a multi-day course (Mon, Wed, Fri for example) to simplify calendars (see the [iCal specification for RRULE](https://icalendar.org/iCalendar-RFC-5545/3-8-5-3-recurrence-rule.html)) and resolves #63 , was not addressed here.

**Comment by natep-tech** [comment]
I broke out the unreviewed part of #325 into it's own PR: #339

**Pull request merged**
