### PR TITLE
RMP popup works again!

### PR DESCRIPTION
**Pull request by Mstrodl**

### CODE REVIEW

**Comment by Mstrodl** [comment]
image
Pretty spiffy!

**Review by joeoneil — APPROVED** [review]

**Comment by natep-tech** [comment]
Obsoletes #334

**Comment by MoralCode** [comment]
Is this likely to interfere with the popup provided by https://github.com/CalvinWu4/RIT-Rate-My-Professors-Extension?

**Comment by Mstrodl** [comment]
> Is this likely to interfere with the popup provided by https://github.com/CalvinWu4/RIT-Rate-My-Professors-Extension?

Probably. I don't use that.

> Does anyone have a citation/evidence that this was a feature in ScheudleMaker before that was just broken versus something that is brand new?

This is an old feature: https://github.com/ComputerScienceHouse/schedulemaker/commit/5e868ce480f3f6d09c7ebe4f504f54f86cbcc2b1#diff-e5e58f8f9ea1db1e486f6520094d1f4d54a7fe0689cc1aa5a28792a7d0b39305

**Pull request merged**
