### PR TITLE
Update Schedule.php to fix iCal Generation

### PR DESCRIPTION
**Pull request by natep-tech**
### Updated the `generateIcal()` function.

1. Updated the code that gets the starting date of the course, to use the weekday number of the term start date. This way if the term starts on a day other than Monday, it'll still correctly generate the start day of the course. #310 #232 

2. Added code that'll generate a single series for a multi-day course (Mon,Web,Fri for example) to simplify calendars (see the [iCal specification for RRULE](https://icalendar.org/iCalendar-RFC-5545/3-8-5-3-recurrence-rule.html)). If any details are different between the different times (different location or times, for example) it'll fallback to the old code that makes separate series for each listed time in the course. #63

### CODE REVIEW

**Comment by natep-tech** [comment]
I need to update the first fix to support term start dates after the first day a class is supposed to start (Term starts Wednesday, so Tuesday/Thursday classes start on Thursday)

**Comment by MoralCode** [comment]
i assume the issues you linked are meant to be resolved when this issue closes, so ill link them as such here:

fixes  #310
fixes #232
fixes #63

**Comment by natep-tech** [comment]
> I need to update the first fix to support term start dates after the first day a class is supposed to start (Term starts Wednesday, so Tuesday/Thursday classes start on Thursday)

Due to the issue #326 I am unable to finish this without correct data.

**Comment by MoralCode** [comment]
@Lontronix are you able to help with this?

**Comment by natep-tech** [comment]
Change number 2, which  generate a single series for a multi-day course (Mon,Web,Fri for example) and resolves #63 , was not addressed with #337 . This PR should stay open until all the features are merged.

**Comment by natep-tech** [comment]
I broke out the unreviewed part into its own PR: #339

**Pull request closed without merging**
